title: Music Courses
author: Романовец Алексей, Будник Кирилл, Доброцкая Мария, Аладко Анастасия
description: > # this means to ignore newlines until "baseurl:"
  Проект "Music Courses"

show_excerpts: true # set to false to remove excerpts on the homepage

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
